### ISSUE TITLE
Failed building

### ISSUE THREAD

**Issue by kadirguloglu** [nandorojo/react-navigation-heavy-screen#1]
It doesn't use the path given in the main tag in package.json file at build time

While trying to resolve module `react-navigation-heavy-screen` from file `D:\Project\aos\app\HalkYatirimAOS\screens\ModelPortfolio\index.js`, the package `D:\Project\aos\app\HalkYatirimAOS\node_modules\react-navigation-heavy-screen\package.json` 
was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`D:\Project\aos\app\HalkYatirimAOS\node_modules\react-navigation-heavy-screen\src\index.tsx`. Indeed, none of these files exist:     

  * D:\Project\aos\app\HalkYatirimAOS\node_modules\react-navigation-heavy-screen\src\index.tsx(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
  * D:\Project\aos\app\HalkYatirimAOS\node_modules\react-navigation-heavy-screen\src\index.tsx\index(.native|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.jsx|.native.expo.jsx|.expo.jsx|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.wasm|.native.wasm|.wasm)
Failed building JavaScript bundle.

**Comment by nandorojo** [comment]
Can I see your code / could you make a snack on snack.expo.io?

**Comment by nandorojo** [comment]
Also, can you confirm that `require('./path/to/Screen').default` doesn't fix it?

**Comment by nandorojo** [comment]
Just checking if updating fixed it. Thanks!

**Comment by nandorojo** [comment]
I haven't heard back, so I'm closing this for now.
