### ISSUE TITLE
Curious why react-native-animatable is a dependency? 

### ISSUE THREAD

**Issue by jforaker** [nandorojo/react-navigation-heavy-screen#26]
There is in package.json: 

```
  "dependencies": {
    "hoist-non-react-statics": "^3.3.2",
    "react-native-animatable": "^1.3.3"
  }
```

yet no usage of `react-native-animatable` in the library. Maybe a leftover and forgot to remove it before publish?

**Comment by nandorojo** [comment]
yeah that’s a mistake, should be removed. haven’t used this lib in a while, it’s not super updated tbh

**Comment by jforaker** [comment]
Thanks @nandorojo 
I ended having to remove heavy screen and replace with a slim custom version because of problems with reanimated (gradle/android/lastest rn etc). I actually used most of your logic  `react-native-animatable` as a substitute after realizing maybe you started with that and moved to reanimated :D  

Thanks for responding, and killer work elsewhere in the ecosystem 👍

**Comment by nandorojo** [comment]
no problem! if you're using native stack this library probably shouldn't even be needed (i no longer use it)
