### ISSUE TITLE
🐛 Does not work with react-native-reanimated >=3.0.0 due to removing the Transition API - Error: Cannot read property 'Together' of undefined

### ISSUE THREAD

**Issue by a-tokyo** [nandorojo/react-navigation-heavy-screen#32]
Facing build error when using reanimated v3. The error is caused by using <Transition.Together> which comes from Reanimated v1 API which is no longer available in v3.

Opened a PR with a fix: https://github.com/nandorojo/react-navigation-heavy-screen/pull/33

**Comment by a-tokyo** [comment]
Similar issue: https://github.com/software-mansion/react-native-reanimated/issues/4156

**Comment by nandorojo** [comment]
this package is pretty old, i would just use native stack now
